apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  labels:
    storage.k8s.io/name: glusterfs
    storage.k8s.io/created-by: liveget
subsets:
  - addresses:
      - ip: 208.xxx.xx.xx
        hostname: master
      - ip: 208.xx.xxx.xx
        hostname: live1
      - ip: 208.xx.xxx.xx
        hostname: live2
    ports:
      - port: 1
